global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'restic-rest-server-demo'

scrape_configs:
  - job_name: 'prometheus' # monitor self
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'rest_server'
    scrape_interval: 5s
    # Uncomment these if you use auth and/or https
    #basic_auth:
    #  username: test
    #  password: test
    #scheme: https
    static_configs:
      - targets: ['restserver:8000']
